export const LOAD_LEADERS_SUCCESS = 'LOAD_LEADERS_SUCCESS';
export const LOAD_LEADERS_FAILURE = 'LOAD_LEADERS_FAILURE';

export const LOAD_ROLES_SUCCESS = 'LOAD_ROLES_SUCCESS';
export const LOAD_ROLES_FAILURE = 'LOAD_ROLES_FAILURE';

export const CREATE_LEADER_SUCCESS = 'CREATE_LEADER_SUCCESS';
export const UPDATE_LEADER_SUCCESS = 'UPDATE_LEADER_SUCCESS';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const END_AJAX_CALL = 'END_AJAX_CALL';
